# action.yml
name: 'Doc-as-Code tester action'
description: 'Perform testing for doc-as-code source files'
inputs:
  file-to-test:
    description: 'Markdown file to test on'
    required: true
    default: 'test.md'
outputs:
  results:
    description: 'Strings with the results of the test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-to-test }}
