# action.yml
name: 'Doc-as-Code tester action'
description: 'Perform testing for doc-as-code source files'
inputs:
  folderPath:
    description: 'Markdown folder containing files to test on'
    required: true
    default: 'src'
outputs:
  results:
    description: 'Strings with the results of the test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folderPath }}
