on: [push, workflow_dispatch]

jobs:
  dac-test-job:
    runs-on: ubuntu-latest
    name: Job test version
    steps:
      - name: Perform repository checkout
        uses: actions/checkout@v2

      - name: Perform test for markdown files
        id: RunTests
        uses: AbianG/dactester-action@initial_rc_version
        with:
          folderPath: 'tests'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The results are ${{ steps.RunTests.outputs.results }}"
