on: [push, workflow_dispatch]

jobs:
  dac-test-job:
    runs-on: ubuntu-latest
    name: A job to test the tester *gasps*
    steps:
      - name: Test a md file
        id: hello
        uses: AbianG/dactester-action@0.01
        with:
          file-to-test: 'filepath_fails.md'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The results are ${{ steps.hello.outputs.results }}"
